#!/usr/bin/env python3
"""Generate build/pins.h from tools/spec.py so the firmware's pin map can't drift from the hardware.

Also cross-checks spec.py against the STM32F103 LQFP-48 datasheet pinout: every
MCU pin whose net is named after a GPIO must sit on that GPIO's package pin.
"""
import os, re, sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tools"))
import spec  # noqa: E402

# DS5319 Table 5, LQFP48 column
LQFP48 = [None, "VBAT", "PC13", "PC14", "PC15", "PD0", "PD1", "NRST", "VSSA", "VDDA",
          "PA0", "PA1", "PA2", "PA3", "PA4", "PA5", "PA6", "PA7", "PB0", "PB1", "PB2",
          "PB10", "PB11", "VSS", "VDD", "PB12", "PB13", "PB14", "PB15", "PA8", "PA9", "PA10",
          "PA11", "PA12", "PA13", "VSS", "VDD", "PA14", "PA15", "PB3", "PB4", "PB5", "PB6",
          "PB7", "BOOT0", "PB8", "PB9", "VSS", "VDD"]
GPIO = re.compile(r"^P([A-D])(\d+)$")

parts = spec.PARTS
mcu = parts["U1"][3]
assert len(mcu) == 48, len(mcu)
for p, net in mcu.items():
    if GPIO.match(net):
        assert LQFP48[int(p)] == net, f"U1.{p} is {LQFP48[int(p)]} but spec net is {net}"

hdr = {}  # net -> "J1.19"
for ref in ("J1", "J3"):
    for p, net in parts[ref][3].items():
        hdr.setdefault(net, f"{ref}.{p}")


def loads(net):
    """On-board parts on this net other than the MCU and headers, e.g. 'R8 10k'."""
    out = []
    for ref, (_, val, _, pins, _) in sorted(parts.items()):
        if ref in ("U1", "J1", "J3"):
            continue
        nets = list(pins.values())
        if net in nets:
            other = sorted({n for n in nets if n != net})
            out.append(f"{ref} {val.split('_')[0]}" + (f" to {'/'.join(other)}" if len(other) == 1 else ""))
    return ", ".join(out)


def c(s):
    return '"' + s.replace('"', '\\"') + '"'


rows, walk = [], []
for p in range(1, 49):
    net = mcu[str(p)]
    fn = LQFP48[p]
    m = GPIO.match(fn)
    port, pin = ("ABCD".index(m.group(1)), int(m.group(2))) if m else (0xFF, 0)
    rows.append(f"  {{{p}, {c(fn)}, {c(net)}, {c(hdr.get(net, '') if net not in spec.POWER_NETS else '')}, {c(spec.ALIASES.get(net, ''))}, "
                f"{c(loads(net) if net not in spec.POWER_NETS else '')}, {port}, {pin}}},")

for ref in ("J1", "J3"):
    for p, net in sorted(parts[ref][3].items(), key=lambda kv: int(kv[0])):
        m = GPIO.match(net)
        if m:
            walk.append(f"  {{{c(net)}, {c(f'{ref}.{p}')}, {'ABCD'.index(m.group(1))}, {int(m.group(2))}}},")

print(f"""/* GENERATED by gen_pins.py from tools/spec.py (rev {spec.REV}) -- do not edit */
#pragma once
#include <stdint.h>
#define BOARD_REV "{spec.REV}"
typedef struct {{ uint8_t lqfp; const char *fn, *net, *hdr, *alias, *loads; uint8_t port, pin; }} mcu_pin_t;
typedef struct {{ const char *name, *hdr; uint8_t port, pin; }} hdr_pin_t;
static const mcu_pin_t MCU_PINS[] = {{
{chr(10).join(rows)}
}};
/* header GPIOs in header order (J1 then J3) */
static const hdr_pin_t HDR_PINS[] = {{
{chr(10).join(walk)}
}};
#define N_MCU_PINS (sizeof MCU_PINS / sizeof MCU_PINS[0])
#define N_HDR_PINS (sizeof HDR_PINS / sizeof HDR_PINS[0])""")
assert len(walk) == 33, len(walk)
